name: Example below coverage threshold
on: [push]

jobs:
  docstr-coverage:
    runs-on: ubuntu-latest
    name: Run docstr-coverage example
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docstr-coverage should fail
        uses: skazazes-work/docstr-coverage-action@v1
        with:
          source_dir: src
